### ISSUE TITLE
Ajouter distance de levenshtein

### ISSUE THREAD

**Issue by zeecho** [viroulep/btest#1]
À faire pour mot par mot (mais vérifier que les gens ne soumettent pas un nombre infini de mots)

**Comment by viroulep** [comment]
As far as ruby is concerned, the algorithm is implemented in the [`text`](https://rubygems.org/gems/text/versions/1.3.1) gem.

**Comment by viroulep** [comment]
Fixed in c8d7d149f6a8f581160a812465f89ceb72cbc2fe, when creating the game you can now choose between using Levenshtein distance and using the double Metaphone algorithm.
